<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Title>KoiVM virtualizer</Title>
    <Description>KoiVM virtualizer</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="VMIR\Compiler\**" />
    <EmbeddedResource Remove="VMIR\Compiler\**" />
    <None Remove="VMIR\Compiler\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Confuser.DynCipher" />
    <PackageReference Include="dnlib" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KoiVM.Runtime\KoiVM.Runtime.csproj" />
  </ItemGroup>
</Project>