<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>KoiVM Confuser</Title>
    <Description>KoiVM Confuser Interface</Description>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Confuser.Core" />
    <PackageReference Include="Confuser.Protections" />
    <PackageReference Include="Confuser.Renamer" />
    <PackageReference Include="dnlib" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KoiVM.Runtime\KoiVM.Runtime.csproj" />
    <ProjectReference Include="..\KoiVM\KoiVM.csproj" />
  </ItemGroup>
</Project>